structure SumDistancesToOriginUsingHigherOrderFunctionsTesting = SumDistancesToOriginTestingFn (struct
	val function = SumDistancesToOriginUsingHigherOrderFunctions.sum_distances_to_origin
	val function_name = "sum_distances_to_origin"
end)